name: Check and Publish

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Compile
      run: cargo build --release
